spring:
  application:
    name: 'smart'
  data:
    mongodb:
      database: kotlin

paginacao:
  qtd_por_pagina: 25

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka