eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739
login:
  url:
    path: /users/login

server:
  error:
    include-stacktrace: never